export { default as Login } from './login'
export { default as Signup } from './signup'
export { default as Dashboard } from './dashboard'
export { default as SideBar } from './sidebar'
export { default as BikeBoard } from './bikeBoard'
